---
services:
  tor-services:
    image: chrisbensch/docker-svcs:latest
    container_name: tor-svcs
    network_mode: host
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ./appdata/var/lib/tor:/var/lib/tor
    restart: always
